### ISSUE TITLE
TypeError in New Project (Svelte)

### ISSUE THREAD

**Issue by lorenzolewis** [histoire-dev/histoire#355] opened 2022-11-12 11:21 UTC
### Describe the bug

When creating a Svelte (not SvelteKit, although the same happens) and then installing Histoire, the following error message appears upon creating your first story:
```
Error while collecting story /Users/lorenzolewis/Developer/histoire-svelte-test/src/lib/Counter.story.svelte:
TypeError: Cannot set property target of #<Event> which has only a getter
    at EventTarget.dispatchEvent (/Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/happy-dom/lib/event/EventTarget.js:42:26)
    at /Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/svelte-hmr/runtime/proxy.js:310:10
    at async ViteNodeRunner.directRequest (file:///Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/vite-node/dist/client.mjs:251:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/vite-node/dist/client.mjs:128:12)
    at async request (file:///Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/vite-node/dist/client.mjs:151:16)
    at async /Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/svelte-hmr/runtime/hot-api.js:3:31
    at async ViteNodeRunner.directRequest (file:///Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/vite-node/dist/client.mjs:251:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/vite-node/dist/client.mjs:128:12)
    at async request (file:///Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/vite-node/dist/client.mjs:151:16)
    at async /Users/lorenzolewis/Developer/histoire-svelte-test/node_modules/svelte-hmr/runtime/index.js:1:238
```

I've tried this with npm, yarn, and pnpm and have the same results for each

### Reproduction

Install Svelte, install Histoire, create a story following the guide for svelte, and then try to run.

Reproduction: https://github.com/lorenzolewis/histoire-svelte-test

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 50.81 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 16.1
  npmPackages:
    @histoire/plugin-svelte: ^0.11.7 => 0.11.7 
    histoire: ^0.11.7 => 0.11.7 
    vite: ^3.2.3 => 3.2.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lorenzolewis** [comment] 2022-11-12 15:41
Did some more digging into this, when I'm using node LTS (18.12.1) I don't run into this issue. It's only when I'm using the latest version of node (19.0.1).

**Comment by endigma** [comment] 2022-11-20 19:28
Can reproduce, observing the same node version issue using `asdf`.

**Comment by Akryum** [comment] 2022-12-02 18:18
Looks like it's an issue with happy-dom

**Comment by benmccann** [comment] 2023-01-27 22:16
Should this issue be closed as fixed by https://github.com/histoire-dev/histoire/commit/e4213d3ffb25c40c395c531dea9a5094bff1973b ?

**Closed** 2023-02-05 11:35 UTC
Labels: bug
