### ISSUE TITLE
HstSelect not working

### ISSUE THREAD

**Issue by Hrishikesh-K** [histoire-dev/histoire#216] opened 2022-07-30 10:34 UTC
### Describe the bug

HstSelect is not showing the dropdown. It logs an error in the browser console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$el')
```

<img width="661" alt="image" src="https://user-images.githubusercontent.com/11403551/181906488-d9e07b61-0872-40d0-b11d-e9ada47b50ac.png">

From the stacktrace, this appears to be an issue with another dependency, but wanted to let Histoire know.

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-udktgy

### System Info

```shell
System:
  OS: macOS 12.5
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 307.04 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
  npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-vue: ^3.0.1 => 3.0.1 
    histoire: ^0.8.4 => 0.8.4 
    vite: ^3.0.4 => 3.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment] 2022-07-30 10:38
Duplicate of #206

**Closed by Akryum** 2022-07-30 10:38 UTC
Labels: to triage
