### ISSUE TITLE
Nuxt3 - Lastest Vite 3 release not working

### ISSUE THREAD

**Issue by Rigo-m** [histoire-dev/histoire#194] opened 2022-07-22 10:55 UTC
### Describe the bug

Using latest nuxt 3 edge release, which has been migrated to vite 3 AFAIK, histoire cannot resolve vite config anymore.

@danielroe cc

Let me know if I can help anyhow

### Reproduction

https://stackblitz.com/edit/nuxt-starter-szzksv?file=package.json

### System Info

```shell
(stackblitz)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment] 2022-07-22 11:05
Duplicate of #189

**Closed by Akryum** 2022-07-22 11:05 UTC
Labels: to triage

**Comment by Akryum** [comment] 2022-07-22 13:37
My mistake, fixed by https://github.com/histoire-dev/histoire/commit/64e306a67149195821c7720cd88343bbdf33e1c9
