### ISSUE TITLE
Hooks can only be used inside setup() function

### ISSUE THREAD

**Issue by vanhoofmaarten** [histoire-dev/histoire#148] opened 2022-06-22 14:33 UTC
### Describe the bug

When using hooks inside a story, more specifically in our case with `vue-query`, we receive the following error:

```
Error: vue-query hooks can only be used inside setup() function.
```

Which I find odd, because we use a setup function inside the story.

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-umts5q?file=src%2FTodo.story.vue

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.11 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Chrome Canary: 105.0.5134.0
    Firefox: 98.0.2
    Firefox Developer Edition: 101.0
    Safari: 15.5
    Safari Technology Preview: 16.0
  npmPackages:
    @vitejs/plugin-vue: ^2.3.1 => 2.3.3
    histoire: ^0.7.8 => 0.7.8
    vite: ^2.9.5 => 2.9.9
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NozomuIkuta** [comment] 2022-07-07 18:49
Here is just a memo of my debug.

```
Error: vue-query hooks can only be used inside setup() function.
```

This error message is logged because `getCurrentInstance` function of `vue-demi` returns `null` inside [`useQueryClient` function of `vue-query`](https://github.com/DamianOsipiuk/vue-query/blob/98570c88f0442330ece2b66bff060ed425f86e88/src/vue/useQueryClient.ts).

Note: I confirmed the valued was `null` by running the reproduction app in my local with `node_modules` modified by injecting `console.log`.

**Comment by Akryum** [comment] 2022-07-21 10:29
Should be fixed by https://github.com/histoire-dev/histoire/commit/855103b70bcbc96b0a2ad23b8ac7c347e11f7160

**Closed by Akryum** 2022-07-21 10:29 UTC
Labels: bug

**Comment by vanhoofmaarten** [comment] 2022-07-22 10:57
Hi @Akryum, thank you for fixing! It works on the reproduction, although the console is still outputting the error. Strange behaviour. 🫤
