### ISSUE TITLE
Chooese another 

### ISSUE THREAD

**Issue by Siregar** [histoire-dev/histoire#139] opened 2022-06-15 05:34 UTC
### Clear and concise description of the problem

Currently, the layout grows horizontally over several levels. This can become very confusing on smaller screens or browser windows (see screenshot).

![Bildschirmfoto 2022-06-15 um 07 27 41](https://user-images.githubusercontent.com/31287148/173745214-7c0d4c2d-1d3c-4722-9fc9-32f96505705e.png)

### Suggested solution

You could solve it like StorybookJS and include the 2nd column as expandable sub-items of the respective menu item (see screenshot).

Variants don't need so much vertical space as to justify the current implementation.

#### bad
![Bildschirmfoto 2022-06-15 um 07 27 41](https://user-images.githubusercontent.com/31287148/173746383-7353ef0c-cfeb-488b-8a12-f74f19e8849f.png)

#### better
![Bildschirmfoto 2022-06-15 um 07 32 14](https://user-images.githubusercontent.com/31287148/173746939-ff98c03f-eaba-45dd-8e34-6b2c364fb885.png)

### Alternative

Create a keyboard shortcut to toggle the sections and an accessible overview of all shortctus.

Another solution could be to position the controls and source section underneath each other (s. Screenshot). Although it would then look more like StorybookJS, the space is then better used.

![Bildschirmfoto 2022-06-15 um 07 38 57](https://user-images.githubusercontent.com/31287148/173749432-dcd77b47-c58e-4689-b19b-48123792c1a0.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by Akryum** [comment] 2022-06-15 08:11
Hey! Thank you for posting this issue, but we already have one!

Duplicate of #106

**Closed by Akryum** 2022-06-15 08:11 UTC
Labels: enhancement: to triage

**Comment by Siregar** [comment] 2022-06-15 08:38
You're very welcome. Maybe you can keep my suggested solutions in mind, when you're searching for one. 😊
