### ISSUE TITLE
Dependency conflict - Using Vite 3, but Histoire has Vite 2.9 as dependency

### ISSUE THREAD

**Issue by rasc-br** [histoire-dev/histoire#224] opened 2022-08-02 18:50 UTC
### Describe the bug

As the title says, Histoire is build over Vite 2.9 and can't be used with Vite 3 (without workarounds)

Found: vite@3.0.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.9.0" from histoire@0.8.4
npm ERR! node_modules/histoire
npm ERR!   dev histoire@"0.8.4" from the root project

### Reproduction

```
npm i vite@latest
npm i histoire@latest
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 3.51 GB / 15.68 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-vue: ^3.0.1 => 3.0.1
    vite: ^3.0.4 => 3.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment] 2022-08-02 20:29
Duplicate of #189

**Closed by Akryum** 2022-08-02 20:29 UTC
Labels: to triage
