### ISSUE TITLE
Cannot read properties of undefined (reading 'component') in built book

### ISSUE THREAD

**Issue by kimdanielenra** [histoire-dev/histoire#427] opened 2023-01-18 14:48 UTC
### Describe the bug

Hi,
I currently get a js error when acccessing the preview version of my stories, dev works fine.

```
bundle-main-8d6405fb.js:45026 Uncaught TypeError: Cannot read properties of undefined (reading 'component')
    at mapFile (bundle-main-8d6405fb.js:45026:34)
    at bundle-main-8d6405fb.js:45782:20
```

I checked the call stack and saw that the error occurs when histoire tries to to read query parameters, which do not exist. This happens on the root route (http://localhost:6006/) as well as component specific routes (http://localhost:6006/story/src-components-3d-3dviewer-story-vue)

![Bildschirmfoto 2023-01-18 um 12 16 45](https://user-images.githubusercontent.com/105912951/213199789-49532a16-a5b9-4d65-894a-bb17ce2de056.png)

### Reproduction

I created a new repo based on my code but removed most of my code to get a minimal example:

[https://github.com/kimdanielenra/histoire-preview-fail](https://github.com/kimdanielenra/histoire-preview-fail)

```
npm install
npm run story:build
npm run story:preview
```

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.20 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 108.1.46.134
    Chrome: 109.0.5414.87
    Firefox: 108.0.1
    Firefox Developer Edition: 109.0
    Safari: 16.0
  npmPackages:
    @histoire/plugin-vue: ^0.12.4 => 0.12.4 
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    histoire: ^0.12.4 => 0.12.4 
    vite: ^4.0.4 => 4.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oneezy** [comment] 2023-01-25 23:36
Same issue on this end w/ sveltekit + histoire version

I can `histoire dev` and `histoire build` just fine but it breaks on `histoire preview` .

**Comment by Goldiggy** [comment] 2023-02-07 17:46
> Same issue on this end w/ sveltekit + histoire version
> 
> I can `histoire dev` and `histoire build` just fine but it breaks on `histoire preview` .

Up because I encounter the same issue. It prevents me from deploying my histoire with vercel 😔

It is caused by the following error in the vendor file: `Uncaught ReferenceError: Buffer is not defined`

**Comment by Akryum** [comment] 2023-02-08 11:33
@Goldiggy this looks like to be another issue fixed by https://github.com/histoire-dev/histoire/commit/3d72efd121098ba0c13ac3d59f3e4900a51269c3

**Closed** 2023-02-08 11:41 UTC
Labels: to triage
